/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIsConfirmationBiasRouteImport } from './routes/what-is-confirmation-bias'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as ConclusionRouteImport } from './routes/conclusion'
import { Route as IndexRouteImport } from './routes/index'

const WhatIsConfirmationBiasRoute = WhatIsConfirmationBiasRouteImport.update({
  id: '/what-is-confirmation-bias',
  path: '/what-is-confirmation-bias',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const ConclusionRoute = ConclusionRouteImport.update({
  id: '/conclusion',
  path: '/conclusion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conclusion': typeof ConclusionRoute
  '/examples': typeof ExamplesRoute
  '/mission': typeof MissionRoute
  '/quiz': typeof QuizRoute
  '/solutions': typeof SolutionsRoute
  '/what-is-confirmation-bias': typeof WhatIsConfirmationBiasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conclusion': typeof ConclusionRoute
  '/examples': typeof ExamplesRoute
  '/mission': typeof MissionRoute
  '/quiz': typeof QuizRoute
  '/solutions': typeof SolutionsRoute
  '/what-is-confirmation-bias': typeof WhatIsConfirmationBiasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conclusion': typeof ConclusionRoute
  '/examples': typeof ExamplesRoute
  '/mission': typeof MissionRoute
  '/quiz': typeof QuizRoute
  '/solutions': typeof SolutionsRoute
  '/what-is-confirmation-bias': typeof WhatIsConfirmationBiasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conclusion'
    | '/examples'
    | '/mission'
    | '/quiz'
    | '/solutions'
    | '/what-is-confirmation-bias'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conclusion'
    | '/examples'
    | '/mission'
    | '/quiz'
    | '/solutions'
    | '/what-is-confirmation-bias'
  id:
    | '__root__'
    | '/'
    | '/conclusion'
    | '/examples'
    | '/mission'
    | '/quiz'
    | '/solutions'
    | '/what-is-confirmation-bias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConclusionRoute: typeof ConclusionRoute
  ExamplesRoute: typeof ExamplesRoute
  MissionRoute: typeof MissionRoute
  QuizRoute: typeof QuizRoute
  SolutionsRoute: typeof SolutionsRoute
  WhatIsConfirmationBiasRoute: typeof WhatIsConfirmationBiasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-is-confirmation-bias': {
      id: '/what-is-confirmation-bias'
      path: '/what-is-confirmation-bias'
      fullPath: '/what-is-confirmation-bias'
      preLoaderRoute: typeof WhatIsConfirmationBiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conclusion': {
      id: '/conclusion'
      path: '/conclusion'
      fullPath: '/conclusion'
      preLoaderRoute: typeof ConclusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConclusionRoute: ConclusionRoute,
  ExamplesRoute: ExamplesRoute,
  MissionRoute: MissionRoute,
  QuizRoute: QuizRoute,
  SolutionsRoute: SolutionsRoute,
  WhatIsConfirmationBiasRoute: WhatIsConfirmationBiasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
